Fix compilation warnings
noonfom/mbed-os pull request #1
Opened 2020-11-09 18:13 UTC by noonfom

### Summary of changes 
Recently, a user found that compiling Mbed OS with the GCC_ARM toolchain produces several warnings that could affect program reliability (ARMmbed#13604). It is not possible to fix all the warnings since there are a lot of 3rd party components in the tree. Moreover, some of the warnings are doubtful to degrade program reliability as they pertain to unused variables and functions. Nevertheless, simple solutions exist for a few of the warnings and they are contained in this PR.

The attached file is the result of the following command:

`mbed compile -c -m NUCLEO_F446RE -t GCC_ARM &> compout.txt`

[compout.txt](https://github.com/noonfom/mbed-os/files/5512491/compout.txt)

 
      
#### Impact of changes 

#### Migration actions required 

### Documentation 
None

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [x] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [ ] Feature update (New feature / Functionality change / New API)
    [ ] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [ ] No Tests required for this change (E.g docs only update)
    [ ] Covered by existing mbed-os tests (Greentea or Unittest)
    [x] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 
@pan- 
@paul-szczepanek-arm

----------------------------------------------------------------------------------------------------------------

2020-11-09 18:29 UTC, paul-szczepanek-arm commented on connectivity/nanostack/coap-service/source/coap_connection_handler.c
> +                #if COAP_SECURITY_AVAILABLE
align #if to 0 and the line below should not be undented

2020-11-09 18:30 UTC, paul-szczepanek-arm requested changes
Thanks. Please fix indent and add the #ifdefs around the unusued functions:
```[Warning] coap_connection_handler.c@544,12: 'timer_status' defined but not used [-Wunused-function]
[Warning] coap_connection_handler.c@521,13: 'start_timer' defined but not used [-Wunused-function]
[Warning] coap_connection_handler.c@468,12: 'secure_session_recvfrom' defined but not used [-Wunused-function]
[Warning] coap_connection_handler.c@435,12: 'secure_session_sendto' defined but not used [-Wunused-function]```

2020-11-09 18:32 UTC, paul-szczepanek-arm commented on connectivity/nanostack/coap-service/source/coap_connection_handler.c
> +                #endif //COAP_SECURITY_AVAILABLE
```suggestion
#if COAP_SECURITY_AVAILABLE
                coap_security_send_close_alert(cur_ptr->sec_handler);
#endif //COAP_SECURITY_AVAILABLE
```

2020-11-09 18:32 UTC, paul-szczepanek-arm commented on connectivity/nanostack/coap-service/source/coap_connection_handler.c
> +                #endif //COAP_SECURITY_AVAILABLE
same below

2020-11-10 10:29 UTC, noonfom commented on connectivity/nanostack/coap-service/source/coap_connection_handler.c
> +                #endif //COAP_SECURITY_AVAILABLE
Thanks. This has been resolved in commit 9a18366ad9517604fc32354a0357e136be189df7.

2020-11-10 14:29 UTC, paul-szczepanek-arm commented
should be [x] Covered by existing mbed-os tests (Greentea or Unittest)

2020-11-10 14:36 UTC, pan- reviewed
Thanks @noonfom that looks good from my perspective however we have to sync with the Oulu team to understand how they want to upstream changes to the nanostack. 

Can you open a PR against mbed-os ?

2021-02-16 10:28 UTC, closed without merging